In [11]:
import glob

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [12]:
files = glob.glob('../data/raw/*.csv')

dataframes = []

for file in files:
    df = pd.read_csv(file)
    df['source_file'] = file.split('/')[-1]
    dataframes.append(df) 

apartments = pd.concat(dataframes, ignore_index=True)
apartments.head()

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price,source_file
0,f8524536d4b09a0c8ccc0197ec9d7bde,szczecin,blockOfFlats,63.00,3.0,4.0,10.0,1980.0,53.378933,14.625296,...,condominium,concreteSlab,NaN,yes,yes,yes,no,yes,415000,raw\apartments_pl_2023_08.csv
1,accbe77d4b360fea9735f138a50608dd,szczecin,blockOfFlats,36.00,2.0,8.0,10.0,NaN,53.442692,14.559690,...,cooperative,concreteSlab,NaN,no,yes,yes,no,yes,395995,raw\apartments_pl_2023_08.csv
2,8373aa373dbc3fe7ca3b7434166b8766,szczecin,tenement,73.02,3.0,2.0,3.0,NaN,53.452222,14.553333,...,condominium,brick,NaN,no,no,no,no,no,565000,raw\apartments_pl_2023_08.csv
3,0a68cd14c44ec5140143ece75d739535,szczecin,tenement,87.60,3.0,2.0,3.0,NaN,53.435100,14.532900,...,condominium,brick,NaN,yes,yes,no,no,yes,640000,raw\apartments_pl_2023_08.csv
4,f66320e153c2441edc0fe293b54c8aeb,szczecin,blockOfFlats,66.00,3.0,1.0,3.0,NaN,53.410278,14.503611,...,condominium,NaN,NaN,no,no,no,no,no,759000,raw\apartments_pl_2023_08.csv

In [13]:
print('shape: ',apartments.shape)
print('\n')
print('data types:\n',apartments.dtypes)

shape:  (266415, 29)


data types:
 id                          str
city                        str
type                        str
squareMeters            float64
rooms                   float64
floor                   float64
floorCount              float64
buildYear               float64
latitude                float64
longitude               float64
centreDistance          float64
poiCount                float64
schoolDistance          float64
clinicDistance          float64
postOfficeDistance      float64
kindergartenDistance    float64
restaurantDistance      float64
collegeDistance         float64
pharmacyDistance        float64
ownership                   str
buildingMaterial            str
condition                   str
hasParkingSpace             str
hasBalcony                  str
hasElevator                 str
hasSecurity                 str
hasStorageRoom              str
price                     int64
source_file                 str
dtype: object

In [14]:
print('missing percent:\n', (apartments.isnull().sum()/len(apartments) * 100).sort_values(ascending=False))

missing percent:
 condition               74.309630
buildingMaterial        39.929809
type                    22.154533
buildYear               19.480134
floor                   16.217931
hasElevator              5.114577
collegeDistance          2.368485
floorCount               1.412083
clinicDistance           0.292026
restaurantDistance       0.237599
pharmacyDistance         0.134001
postOfficeDistance       0.102847
kindergartenDistance     0.093839
schoolDistance           0.068690
centreDistance           0.000000
longitude                0.000000
latitude                 0.000000
id                       0.000000
city                     0.000000
squareMeters             0.000000
rooms                    0.000000
poiCount                 0.000000
ownership                0.000000
hasParkingSpace          0.000000
hasBalcony               0.000000
hasSecurity              0.000000
hasStorageRoom           0.000000
price                    0.000000
source_file              0.000000
dtype: float64

In [15]:
cols_to_check = [col for col in apartments.columns if col != 'source_file']
print('duplicated values: ', apartments.duplicated(subset=cols_to_check).sum())
print('duplicated values percent: ', round(apartments.duplicated(subset=cols_to_check).sum()/len(apartments) * 100))

duplicated values:  109865
duplicated values percent:  41

In [16]:
apartments.describe()

,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,centreDistance,poiCount,schoolDistance,clinicDistance,postOfficeDistance,kindergartenDistance,restaurantDistance,collegeDistance,pharmacyDistance,price
count,266415.000000,266415.000000,223208.000000,262653.000000,214517.000000,266415.000000,266415.000000,266415.000000,266415.000000,266232.000000,265637.000000,266141.000000,266165.000000,265782.000000,260105.000000,266058.000000,2.664150e+05
mean,57.781554,2.600965,3.356775,5.409034,1988.870206,51.962273,19.525827,4.219511,21.878269,0.400989,0.918584,0.504065,0.356822,0.322840,1.401178,0.345021,5.766722e+05
std,21.808572,0.913106,2.564715,3.356407,33.409773,1.301069,1.758002,2.785979,25.159092,0.435368,0.852449,0.472085,0.415910,0.431425,1.083914,0.427448,4.920273e+05
min,25.000000,1.000000,1.000000,1.000000,1850.000000,49.978999,14.447100,0.010000,0.000000,0.002000,0.001000,0.001000,0.001000,0.001000,0.004000,0.001000,3.460000e+02
25%,42.460000,2.000000,2.000000,3.000000,1970.000000,51.103008,18.543291,1.920000,7.000000,0.176000,0.336000,0.238000,0.155000,0.104000,0.560000,0.141000,8.000000e+03
50%,53.000000,2.000000,3.000000,4.000000,2001.000000,52.193010,19.926100,3.820000,14.000000,0.289000,0.640000,0.391000,0.261000,0.215000,1.072000,0.238000,5.750000e+05
75%,67.580000,3.000000,4.000000,6.000000,2017.000000,52.343422,20.995487,5.970000,26.000000,0.463000,1.161000,0.611000,0.412000,0.391000,2.014000,0.400000,8.250000e+05
max,150.000000,6.000000,30.000000,30.000000,2024.000000,54.606460,23.208873,16.940000,212.000000,4.946000,4.999000,4.970000,4.961000,4.985000,5.000000,4.992000,3.250000e+06